[project]
name = "hull"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kaggle>=1.7.4.5",
    "lightgbm>=4.6.0",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
]
